# https://starship.rs/ja-JP/config/#character
format = """
$username\
$hostname\
$directory\
$git_branch
$character
"""
add_newline = true

[username]
style_user = '#a688bd bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
#aliases = { "corpuser034g" = "matchai" }

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)on [$hostname](bold #ed6d46) '
trim_at = '.companyname.com'
disabled = false

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾" #鍵のicon

[git_branch]
symbol = ''
truncation_length = 30
truncation_symbol = ''
#ignore_branches = ['master', 'main']

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
